In [1]:
import pandas as pd

users = pd.read_csv('users.csv')
users.head()

,id,email,email_confirmed_at,confirmation_sent_at,last_sign_in_at
0,95f8e451-1bc3-4f10-b42b-711f6df89dc5,arshaktavadyan@yandex.ru,2026-03-21 09:57:57.067+00,2026-03-21 09:52:56.386468+00,2026-03-21 09:59:16.339331+00
1,f28ed940-e77e-4f7b-bcda-39a944827f38,sklochkov.mail@gmail.com,2026-03-23 19:13:27.851658+00,2026-03-23 19:13:14.974776+00,2026-03-23 19:30:38.699657+00
2,25c20f46-73fb-4104-835f-ff02e180b149,xynd.alexandr@gmail.com,2026-03-22 13:35:06.029573+00,2026-03-22 13:34:52.958426+00,2026-03-22 13:37:10.732488+00
3,003f0c5c-a60d-4ca5-9a5b-9381fa44cc8b,ogneva.masha@gmail.com,2026-03-21 08:05:53.108637+00,2026-03-21 08:05:36.999871+00,2026-03-21 08:06:08.442643+00
4,fc9bcb14-2484-404f-9af3-dcb406ef3a07,niki.angelina.45@gmail.com,2026-03-20 15:07:09.862856+00,2026-03-20 15:06:32.388125+00,2026-03-20 15:11:15.832643+00

In [3]:
raw_events = pd.read_csv('events_raw.csv')
raw_events.head()

,event,page_url,params_json,created_at,user_id
0,page_view,/auth/confirmed,"{""url"":""/auth/confirmed#access_token=eyJhbGciO...",2026-03-19 16:40:57,47fc1ec2-4dc2-4b70-9df2-d1864152102d
1,page_view,/,"{""url"":""/""}",2026-03-19 16:41:08,90a8d48d-8900-46cf-875a-25883a94c1c8
2,page_view,/,"{""url"":""/""}",2026-03-19 16:47:49,eb39e8e2-3fd1-43ff-9cfa-fcf8ec221852
3,page_view,/,"{""url"":""/""}",2026-03-19 16:47:50,fdc9ca3a-db2e-4150-8279-5ac0eb1bb797
4,page_view,/,"{""url"":""/""}",2026-03-19 16:51:17,afcb3a69-04ab-403f-8952-255004ecec5f

In [4]:
raw_events.shape[0]

1171